config/routes.rb
Rails.application.routes.draw do
  get 'comments/new'
  get 'comments/create'
  get 'comments/show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]
  resources :comments, only: [:create, :show]
  resources :subs, except: [:destroy]
  resources :posts, except: [:destroy, :index] do
    resources :comments, only: [:new]
  end

  root to: redirect('/subs')
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, presence: true
    validates :subs, presence: { message: 'must have at least one sub' }

    has_many :post_subs, inverse_of: :post, dependent: :destroy
    has_many :subs, through: :post_subs, source: :sub
    has_many :comments, inverse_of: :post

    belongs_to :author,
        class_name: :User,
        foreign_key: :user_id,
        inverse_of: :posts

    def comments_by_parent
        comments_by_parent = Hash.new { |hash, key| hash[key] = [] }

        self.comments.includes(:author).each do |comment|
            comments_by_parent[comment.parent_comment_id] << comment
        end

        comments_by_parent
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_signed_in!, except: [:show]
  before_action :require_user_owns_post!, only: [:edit, :update]

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  private

  def post_params
    params.require(:post).permit(
      :title, :url, :content, :user_id, sub_ids: []
    )
  end

  def require_user_owns_post!
    return if current_user.posts.find_by(id: params[:id])
    render json: 'Forbidden', status: :forbidden
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<% action_url = post.persisted? ? post_url(post) : posts_url %>
<% http_method = post.persisted? ? "PATCH" : "POST" %>

<form action="<%= action_url %>" method="post">
    <input type="hidden" name="_method" value="<%= http_method %>">
    <%= auth_token %>

    <label>
        Title:
        <input name="post[title]" value="<%= post.title %>">
    </label>
    <br>

    <label>
        URL:
        <input name="post[url]" value="<%= post.url %>">
    </label>
    <br>

    <label>
        Content:
        <textarea name="post[content]"><%= post.content %></textarea>
    </label>
    <br>

    <input type="hidden" name="post[sub_ids][]" value="">
    <% Sub.all.each do |sub| %>
    <label>
        <input
            type="checkbox"
            name="post[sub_ids][]"
            value="<%= sub.id %>"
            <%= "checked" if post.sub_ids.include?(sub.id) %>>
        <%= sub.name %>
    </label>
    <br>
    <% end %>

    <input type="submit" value="Submit">
</form>

app/views/posts/edit.html.erb
<div class="border">
    <h1>Edit Post!</h1>
    
    <%= render "form", post: @post %>
</div>

app/views/posts/new.html.erb
<h1>Posts#new</h1>
<p>Find me in app/views/posts/new.html.erb</p>

app/views/posts/show.html.erb
<div class="border">
    <h1>
        <a href="<%= post_url(@post) %>"><%= @post.title %></a> by
        <%= @post.author.name %>
    </h1>

    <div class="small-border">
        <b>Content:</b>

        <pre><%= @post.content %></pre>
        <br><br>
    </div>

    <br>
    <b>Subs</b>
    <ul>
        <% @post.subs.each do |sub| %>
            <li><a href="<%= sub_url(sub) %>"><%= sub.name %></a></li>
        <% end %>
    </ul>

    <h2>Comments</h2>

    <a href="<%= new_post_comment_url(@post.id) %>">Comment on this post!</a>
    <br><br>

    <ul>
        <% comments_by_parent = @post.comments_by_parent %>
        <% comments_by_parent[nil].each do |top_level_comment| %>
            <li>
                <%= render("comments/comment",
                            comment: top_level_comment,
                            comments_by_parent: comments_by_parent) %>
            </li>
        <% end %>
    </ul>

    <a href="<%= edit_post_url(@post) if @post.author == current_user %>">Edit</a>
</div>